#!/usr/bin/env node
/**
 * Generate placeholder icons for Tauri builds.
 * Real icons will be added once the design system is finalized.
 * This script creates a minimal valid PNG so `tauri build` does not fail.
 */
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const iconsDir = join(__dirname, '..', 'apps', 'desktop', 'src-tauri', 'icons');

if (!existsSync(iconsDir)) {
  mkdirSync(iconsDir, { recursive: true });
}

// 1x1 transparent PNG (base64)
const PNG_1x1 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=';

const sizes = ['32x32.png', '128x128.png', '128x128@2x.png', 'icon.png'];
for (const name of sizes) {
  writeFileSync(join(iconsDir, name), Buffer.from(PNG_1x1, 'base64'));
  console.log(`✓ ${name}`);
}

// .ico and .icns need to be generated by tools; create empty placeholders
writeFileSync(join(iconsDir, 'icon.ico'), Buffer.from(PNG_1x1, 'base64'));
writeFileSync(join(iconsDir, 'icon.icns'), Buffer.from(PNG_1x1, 'base64'));
console.log('✓ icon.ico, icon.icns (placeholders)');
console.log('Replace these with real icons before release!');
